# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(645, 547)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.filepath = QtWidgets.QLineEdit(self.centralwidget)
        self.filepath.setMinimumSize(QtCore.QSize(0, 30))
        self.filepath.setObjectName("filepath")
        self.verticalLayout.addWidget(self.filepath)
        self.browse_btn = QtWidgets.QPushButton(self.centralwidget)
        self.browse_btn.setObjectName("browse_btn")
        self.verticalLayout.addWidget(self.browse_btn)
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.start_btn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout.addWidget(self.start_btn, 0, QtCore.Qt.AlignRight)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.browse_btn.setText(_translate("MainWindow", "Browse"))
        self.start_btn.setText(_translate("MainWindow", "START PLOT"))
