# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\tviks\Desktop\GitHub\nauchnaya_praktika\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1026, 876)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 5, 1, 1)
        self.pic_lable = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pic_lable.sizePolicy().hasHeightForWidth())
        self.pic_lable.setSizePolicy(sizePolicy)
        self.pic_lable.setMinimumSize(QtCore.QSize(750, 750))
        self.pic_lable.setMaximumSize(QtCore.QSize(1000, 1000))
        self.pic_lable.setText("")
        self.pic_lable.setObjectName("pic_lable")
        self.gridLayout.addWidget(self.pic_lable, 2, 1, 1, 4, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.folder_btn = QtWidgets.QPushButton(self.centralwidget)
        self.folder_btn.setMinimumSize(QtCore.QSize(150, 50))
        self.folder_btn.setObjectName("folder_btn")
        self.gridLayout.addWidget(self.folder_btn, 0, 2, 1, 1)
        self.file_list = QtWidgets.QListWidget(self.centralwidget)
        self.file_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.file_list.setObjectName("file_list")
        self.gridLayout.addWidget(self.file_list, 0, 0, 4, 1)
        self.plot_btn = QtWidgets.QPushButton(self.centralwidget)
        self.plot_btn.setMinimumSize(QtCore.QSize(200, 50))
        self.plot_btn.setObjectName("plot_btn")
        self.gridLayout.addWidget(self.plot_btn, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        self.pic_lable.raise_()
        self.folder_btn.raise_()
        self.file_list.raise_()
        self.plot_btn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.folder_btn.setText(_translate("MainWindow", "Select data"))
        self.plot_btn.setText(_translate("MainWindow", "Create Plot"))
